name: vibeon
description: VibeOn - Music & Video sharing app (expanded)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.12.2
  firebase_storage: ^11.3.2
  firebase_messaging: ^14.7.5
  google_sign_in: ^6.2.1
  video_player: ^2.7.0
  chewie: ^1.6.0
  just_audio: ^0.9.34
  file_picker: ^5.3.2
  image_picker: ^1.0.4
  permission_handler: ^11.1.0
  connectivity_plus: ^6.0.3
  share_plus: ^7.2.2
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
